### ISSUE TITLE
Client blinks

### ISSUE THREAD

**Issue by fominok** [little-dude/xi-tui#89]
When cursor moves fast like on constant holding down key I see how xi-term blinks, like redrawing or something. Checked in Alacritty and xfce4-terminal. Is it a config issue or a bug?

**Comment by patrickisgreene** [comment]
It is a bug. It because currently we are rendering every line in the view on every frame

**Comment by fominok** [comment]
@bytebuddha, there is a fix in #90, could you take a look?

**Comment by c4eater** [comment]
Hi folks,

#90 doesn't fix this problem. It only presents an optimization that reduces stress on buffer writing.

The bug is still present (my case: xterm on linux).

A bit of explanation: The screen **always** flickers when the user makes a few force-redraws in rapid succession (eg when the cursor is moved down with a down arrow key). To make this flickering happen, you don't even need to run xi-term. Consider the following simple console application which prints out the file and redraws everything when the user presses any key:

```rust
use std::env;
use std::fs;
use std::io::{Read,Write};
use termios::*;

fn main() {
    let args: Vec<String> = env::args().collect();

    if args.len() != 2 {
        eprintln!("Usage: {} FILENAME", args[0]);
        return;
    }

    let filename = &args[1];
    let contents = fs::read_to_string(filename).unwrap();

    // disable terminal buffering so that keypress is read() immediately
    let mut termios_info = Termios::from_fd(0).unwrap();
    tcgetattr(0, &mut termios_info);
    termios_info.c_lflag &= !ICANON;
    termios_info.c_cc[VMIN] = 1;
    termios_info.c_cc[VTIME] = 0;
    tcsetattr(0, TCSANOW, &termios_info);

    let stdin = std::io::stdin();
    let mut handle = stdin.lock();
    let key = 0u8;

    while true {
        // any key = redraw
        // Ctrl+C = exit
        handle.read(&mut[key]);

        write!(std::io::stdout(), "{}", contents);
    }
}
```
Hit or hold down any key and observe the screen flickering.

Suggestion: Reopen the bug; Write some code that remembers the start and the end line numbers of the currently rendered portion of LineCache. If an event does not take us out of this "frame", redraw only the cursor, not the lines.

**Comment by c4eater** [comment]
@fominok / @bytebuddha can you please comment on this? The blinking is definitely present.

I confirm that this is happening due to frequent re-rendering of all window lines. I wrote a view.rs hack that skips render_lines() if linecache didn't change and that fixed the blinking. It's not a proper fix; I was using a full backup of the visible lines and then a linewise comparison between the backup and the current linecache slice, which is highly ineffective. Currently the LineCache is simply not able of notifying its users of any atomic change in its contents, so my opinion is that we need a "RenderCache" instead of "LineCache". This "RenderCache" should be aware both of the incoming vector of ops from xi-core and of the rendering, and call render_lines only for the modified lines.

Having that said, also pls consider xi-editor/xi-editor#1228: it seems that xi-core even cannot properly notify the client of a cursor move that does not modify the lines.

Side question: Is anyone ever using xi-term on a daily basis? I'm pretty much surprised that no one is complaining on blinking or on crashing on files as small as 65kb (#112), given the fact that those bugs hit you in the face as soon as you start editing real files with xi-term.

**Comment by fominok** [comment]
As you rightly said, my fix was an optimization to move from "annoying" to "ok for now" state of blinking.
Personally I'm waiting for Xi SDK to reuse its components for standalone editors as the protocol cannot fit anything and something like modal editing needs to be implemented on the client-side, or there is a need to introduce something like middleware. Answering your last question: this prevents me from using xi-term.
Also, I think you have experience with this and you can propose the right changes to Xi-core (and ping guys on zulip)

**Comment by c4eater** [comment]
Have a reply from the xi-core devs, see the talk on the xi-core issue page.

Bottom line: this may become a todo item for xi-core in future, but for the time being, xrl / xi-term would better rely on the protocol as it is.

That said, this problem can be solved on the client (xrl::LineCache side) by introducing a line-level cache invalidation (= a "dirty" bit attached to every cache line), so that the cache could announce that only the given (few) lines were changed and need a redraw.

My understanding is that there is an ongoing work on turning xrl::LineCache into a hash map so this "cache invalidation" objective should better be put on hold until this hash map thing is complete.
